image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

services:
  - mongo
  
install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  
test_with_lab:
  stage: test
  script: 
    - npm run test:unit
    